//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_Diagram_Modeler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ER_Diagram_Modeler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DataTypes&gt;
        ///	&lt;t Name=&quot;bigint&quot; MaxLenght=&quot;8&quot; Precision=&quot;19&quot; Scale=&quot;0&quot; IsNullable=&quot;1&quot; HasLenght=&quot;0&quot; HasPrecision=&quot;0&quot; HasScale=&quot;0&quot; DefaultLenght=&quot;0&quot; DefaultPrecision=&quot;0&quot; DefaultScale=&quot;0&quot; /&gt;
        ///	&lt;t Name=&quot;binary&quot; MaxLenght=&quot;8000&quot; Precision=&quot;0&quot; Scale=&quot;0&quot; IsNullable=&quot;1&quot; HasLenght=&quot;1&quot; HasPrecision=&quot;0&quot; HasScale=&quot;0&quot; DefaultLenght=&quot;8&quot; DefaultPrecision=&quot;0&quot; DefaultScale=&quot;0&quot; /&gt;
        ///	&lt;t Name=&quot;bit&quot; MaxLenght=&quot;1&quot; Precision=&quot;1&quot; Scale=&quot;0&quot; IsNullable=&quot;1&quot; HasLenght=&quot;0&quot; HasPrecision=&quot;0&quot; HasSca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataTypesMicrosoft {
            get {
                return ResourceManager.GetString("DataTypesMicrosoft", resourceCulture);
            }
        }
    }
}
